"""make_content_not_nullable

Revision ID: 2e084b795fc9
Revises: 9c44fba64e21
Create Date: 2026-02-08 05:42:22.807369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e084b795fc9'
down_revision: Union[str, Sequence[str], None] = '9c44fba64e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
