"""add_user_id_to_statuses

Revision ID: 2f6a337a00d2
Revises: 87d53b4d8980
Create Date: 2026-02-20 14:44:52.555960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f6a337a00d2'
down_revision: Union[str, Sequence[str], None] = '87d53b4d8980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. nullable で追加
    op.add_column('statuses', sa.Column('user_id', sa.Integer(), nullable=True))

    # 2. 既存行を最初のユーザーに紐付け
    op.execute(
        "UPDATE statuses SET user_id = (SELECT id FROM users ORDER BY id LIMIT 1) WHERE user_id IS NULL"
    )

    # 3. not null に変更
    op.alter_column('statuses', 'user_id', nullable=False)

    op.drop_constraint(op.f('statuses_name_key'), 'statuses', type_='unique')
    op.create_index(op.f('ix_statuses_user_id'), 'statuses', ['user_id'], unique=False)
    op.create_foreign_key(None, 'statuses', 'users', ['user_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statuses', type_='foreignkey')
    op.drop_index(op.f('ix_statuses_user_id'), table_name='statuses')
    op.create_unique_constraint(op.f('statuses_name_key'), 'statuses', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('statuses', 'user_id')
    # ### end Alembic commands ###
