"""create statuses table and add status_id to tasks

Revision ID: 3f6f79c0f782
Revises: 2e084b795fc9
Create Date: 2026-02-11 06:16:26.237424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6f79c0f782'
down_revision: Union[str, Sequence[str], None] = '2e084b795fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_statuses_order'), 'statuses', ['order'], unique=False)
    op.add_column('tasks', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'status_id')
    op.drop_index(op.f('ix_statuses_order'), table_name='statuses')
    op.drop_table('statuses')
    # ### end Alembic commands ###
