/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Task Management API
 * FastAPI + React Todo App
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { client } from './client';
export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

/**
 * ソート順
 */
export type SortOrder = typeof SortOrder[keyof typeof SortOrder];


export const SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

/**
 * タスク作成用スキーマ
 */
export interface TaskCreate {
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  content: string;
  due_date: string;
}

/**
 * タスクレスポンス用スキーマ
 */
export interface TaskResponse {
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  content: string;
  due_date: string;
  id: number;
  created_at: string;
  updated_at: string;
}

/**
 * タスク一覧レスポンス用スキーマ
 */
export interface TaskListResponse {
  tasks: TaskResponse[];
}

/**
 * タスク更新用スキーマ
 */
export interface TaskUpdate {
  /**
   * @minLength 1
   * @maxLength 255
   */
  title: string;
  content: string;
  due_date: string;
}

export type ListTasksTasksGetParams = {
order?: SortOrder;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * タスク一覧取得（締切日でソート）
 * @summary List Tasks
 */
export const getListTasksTasksGetUrl = (params?: ListTasksTasksGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/tasks?${stringifiedParams}` : `/tasks`
}

export const listTasksTasksGet = async (params?: ListTasksTasksGetParams, options?: RequestInit): Promise<TaskListResponse> => {
  
  return client<TaskListResponse>(getListTasksTasksGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListTasksTasksGetQueryKey = (params?: ListTasksTasksGetParams,) => {
    return [
    `/tasks`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListTasksTasksGetQueryOptions = <TData = Awaited<ReturnType<typeof listTasksTasksGet>>, TError = HTTPValidationError>(params?: ListTasksTasksGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTasksTasksGet>>, TError, TData>>, request?: SecondParameter<typeof client>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTasksTasksGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTasksTasksGet>>> = ({ signal }) => listTasksTasksGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTasksTasksGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTasksTasksGetQueryResult = NonNullable<Awaited<ReturnType<typeof listTasksTasksGet>>>
export type ListTasksTasksGetQueryError = HTTPValidationError


export function useListTasksTasksGet<TData = Awaited<ReturnType<typeof listTasksTasksGet>>, TError = HTTPValidationError>(
 params: undefined |  ListTasksTasksGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTasksTasksGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTasksTasksGet>>,
          TError,
          Awaited<ReturnType<typeof listTasksTasksGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof client>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTasksTasksGet<TData = Awaited<ReturnType<typeof listTasksTasksGet>>, TError = HTTPValidationError>(
 params?: ListTasksTasksGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTasksTasksGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTasksTasksGet>>,
          TError,
          Awaited<ReturnType<typeof listTasksTasksGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof client>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTasksTasksGet<TData = Awaited<ReturnType<typeof listTasksTasksGet>>, TError = HTTPValidationError>(
 params?: ListTasksTasksGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTasksTasksGet>>, TError, TData>>, request?: SecondParameter<typeof client>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Tasks
 */

export function useListTasksTasksGet<TData = Awaited<ReturnType<typeof listTasksTasksGet>>, TError = HTTPValidationError>(
 params?: ListTasksTasksGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTasksTasksGet>>, TError, TData>>, request?: SecondParameter<typeof client>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTasksTasksGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * タスク作成
 * @summary Create Task
 */
export const getCreateTaskTasksPostUrl = () => {


  

  return `/tasks`
}

export const createTaskTasksPost = async (taskCreate: TaskCreate, options?: RequestInit): Promise<TaskResponse> => {
  
  return client<TaskResponse>(getCreateTaskTasksPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      taskCreate,)
  }
);}




export const getCreateTaskTasksPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTaskTasksPost>>, TError,{data: TaskCreate}, TContext>, request?: SecondParameter<typeof client>}
): UseMutationOptions<Awaited<ReturnType<typeof createTaskTasksPost>>, TError,{data: TaskCreate}, TContext> => {

const mutationKey = ['createTaskTasksPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTaskTasksPost>>, {data: TaskCreate}> = (props) => {
          const {data} = props ?? {};

          return  createTaskTasksPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTaskTasksPostMutationResult = NonNullable<Awaited<ReturnType<typeof createTaskTasksPost>>>
    export type CreateTaskTasksPostMutationBody = TaskCreate
    export type CreateTaskTasksPostMutationError = HTTPValidationError

    /**
 * @summary Create Task
 */
export const useCreateTaskTasksPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTaskTasksPost>>, TError,{data: TaskCreate}, TContext>, request?: SecondParameter<typeof client>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTaskTasksPost>>,
        TError,
        {data: TaskCreate},
        TContext
      > => {
      return useMutation(getCreateTaskTasksPostMutationOptions(options), queryClient);
    }
    
/**
 * タスク詳細取得
 * @summary Get Task
 */
export const getGetTaskTasksTaskIdGetUrl = (taskId: number,) => {


  

  return `/tasks/${taskId}`
}

export const getTaskTasksTaskIdGet = async (taskId: number, options?: RequestInit): Promise<TaskResponse> => {
  
  return client<TaskResponse>(getGetTaskTasksTaskIdGetUrl(taskId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetTaskTasksTaskIdGetQueryKey = (taskId: number,) => {
    return [
    `/tasks/${taskId}`
    ] as const;
    }

    
export const getGetTaskTasksTaskIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getTaskTasksTaskIdGet>>, TError = HTTPValidationError>(taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskTasksTaskIdGet>>, TError, TData>>, request?: SecondParameter<typeof client>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTaskTasksTaskIdGetQueryKey(taskId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTaskTasksTaskIdGet>>> = ({ signal }) => getTaskTasksTaskIdGet(taskId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(taskId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTaskTasksTaskIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTaskTasksTaskIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTaskTasksTaskIdGet>>>
export type GetTaskTasksTaskIdGetQueryError = HTTPValidationError


export function useGetTaskTasksTaskIdGet<TData = Awaited<ReturnType<typeof getTaskTasksTaskIdGet>>, TError = HTTPValidationError>(
 taskId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskTasksTaskIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskTasksTaskIdGet>>,
          TError,
          Awaited<ReturnType<typeof getTaskTasksTaskIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof client>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaskTasksTaskIdGet<TData = Awaited<ReturnType<typeof getTaskTasksTaskIdGet>>, TError = HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskTasksTaskIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskTasksTaskIdGet>>,
          TError,
          Awaited<ReturnType<typeof getTaskTasksTaskIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof client>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaskTasksTaskIdGet<TData = Awaited<ReturnType<typeof getTaskTasksTaskIdGet>>, TError = HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskTasksTaskIdGet>>, TError, TData>>, request?: SecondParameter<typeof client>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Task
 */

export function useGetTaskTasksTaskIdGet<TData = Awaited<ReturnType<typeof getTaskTasksTaskIdGet>>, TError = HTTPValidationError>(
 taskId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskTasksTaskIdGet>>, TError, TData>>, request?: SecondParameter<typeof client>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTaskTasksTaskIdGetQueryOptions(taskId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * タスク更新
 * @summary Update Task
 */
export const getUpdateTaskTasksTaskIdPutUrl = (taskId: number,) => {


  

  return `/tasks/${taskId}`
}

export const updateTaskTasksTaskIdPut = async (taskId: number,
    taskUpdate: TaskUpdate, options?: RequestInit): Promise<TaskResponse> => {
  
  return client<TaskResponse>(getUpdateTaskTasksTaskIdPutUrl(taskId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      taskUpdate,)
  }
);}




export const getUpdateTaskTasksTaskIdPutMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTaskTasksTaskIdPut>>, TError,{taskId: number;data: TaskUpdate}, TContext>, request?: SecondParameter<typeof client>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTaskTasksTaskIdPut>>, TError,{taskId: number;data: TaskUpdate}, TContext> => {

const mutationKey = ['updateTaskTasksTaskIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTaskTasksTaskIdPut>>, {taskId: number;data: TaskUpdate}> = (props) => {
          const {taskId,data} = props ?? {};

          return  updateTaskTasksTaskIdPut(taskId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTaskTasksTaskIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateTaskTasksTaskIdPut>>>
    export type UpdateTaskTasksTaskIdPutMutationBody = TaskUpdate
    export type UpdateTaskTasksTaskIdPutMutationError = HTTPValidationError

    /**
 * @summary Update Task
 */
export const useUpdateTaskTasksTaskIdPut = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTaskTasksTaskIdPut>>, TError,{taskId: number;data: TaskUpdate}, TContext>, request?: SecondParameter<typeof client>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTaskTasksTaskIdPut>>,
        TError,
        {taskId: number;data: TaskUpdate},
        TContext
      > => {
      return useMutation(getUpdateTaskTasksTaskIdPutMutationOptions(options), queryClient);
    }
    
/**
 * タスク削除
 * @summary Delete Task
 */
export const getDeleteTaskTasksTaskIdDeleteUrl = (taskId: number,) => {


  

  return `/tasks/${taskId}`
}

export const deleteTaskTasksTaskIdDelete = async (taskId: number, options?: RequestInit): Promise<void> => {
  
  return client<void>(getDeleteTaskTasksTaskIdDeleteUrl(taskId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteTaskTasksTaskIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTaskTasksTaskIdDelete>>, TError,{taskId: number}, TContext>, request?: SecondParameter<typeof client>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTaskTasksTaskIdDelete>>, TError,{taskId: number}, TContext> => {

const mutationKey = ['deleteTaskTasksTaskIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTaskTasksTaskIdDelete>>, {taskId: number}> = (props) => {
          const {taskId} = props ?? {};

          return  deleteTaskTasksTaskIdDelete(taskId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTaskTasksTaskIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTaskTasksTaskIdDelete>>>
    
    export type DeleteTaskTasksTaskIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Task
 */
export const useDeleteTaskTasksTaskIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTaskTasksTaskIdDelete>>, TError,{taskId: number}, TContext>, request?: SecondParameter<typeof client>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTaskTasksTaskIdDelete>>,
        TError,
        {taskId: number},
        TContext
      > => {
      return useMutation(getDeleteTaskTasksTaskIdDeleteMutationOptions(options), queryClient);
    }
