/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Task Management API
 * FastAPI + React Todo App
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * タスク一覧取得（締切日でソート）
 * @summary List Tasks
 */
export const ListTasksTasksGetQueryParams = zod.object({
  "order": zod.enum(['asc', 'desc']).optional()
})

export const listTasksTasksGetResponseTasksItemTitleMax = 255;



export const ListTasksTasksGetResponse = zod.object({
  "tasks": zod.array(zod.object({
  "title": zod.string().min(1).max(listTasksTasksGetResponseTasksItemTitleMax),
  "content": zod.string(),
  "due_date": zod.iso.date(),
  "id": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('タスクレスポンス用スキーマ'))
}).describe('タスク一覧レスポンス用スキーマ')


/**
 * タスク作成
 * @summary Create Task
 */
export const createTaskTasksPostBodyTitleMax = 255;



export const CreateTaskTasksPostBody = zod.object({
  "title": zod.string().min(1).max(createTaskTasksPostBodyTitleMax),
  "content": zod.string(),
  "due_date": zod.iso.date()
}).describe('タスク作成用スキーマ')


/**
 * タスク詳細取得
 * @summary Get Task
 */
export const GetTaskTasksTaskIdGetParams = zod.object({
  "task_id": zod.number()
})

export const getTaskTasksTaskIdGetResponseTitleMax = 255;



export const GetTaskTasksTaskIdGetResponse = zod.object({
  "title": zod.string().min(1).max(getTaskTasksTaskIdGetResponseTitleMax),
  "content": zod.string(),
  "due_date": zod.iso.date(),
  "id": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('タスクレスポンス用スキーマ')


/**
 * タスク更新
 * @summary Update Task
 */
export const UpdateTaskTasksTaskIdPutParams = zod.object({
  "task_id": zod.number()
})

export const updateTaskTasksTaskIdPutBodyTitleMax = 255;



export const UpdateTaskTasksTaskIdPutBody = zod.object({
  "title": zod.string().min(1).max(updateTaskTasksTaskIdPutBodyTitleMax),
  "content": zod.string(),
  "due_date": zod.iso.date()
}).describe('タスク更新用スキーマ')

export const updateTaskTasksTaskIdPutResponseTitleMax = 255;



export const UpdateTaskTasksTaskIdPutResponse = zod.object({
  "title": zod.string().min(1).max(updateTaskTasksTaskIdPutResponseTitleMax),
  "content": zod.string(),
  "due_date": zod.iso.date(),
  "id": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('タスクレスポンス用スキーマ')


/**
 * タスク削除
 * @summary Delete Task
 */
export const DeleteTaskTasksTaskIdDeleteParams = zod.object({
  "task_id": zod.number()
})
