/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Task Management API
 * FastAPI + React Todo App
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * @summary Signup
 */
export const signupAuthSignupPostBodyUsernameMin = 3;
export const signupAuthSignupPostBodyUsernameMax = 150;

export const signupAuthSignupPostBodyPasswordMin = 8;



export const SignupAuthSignupPostBody = zod.object({
  "username": zod.string().min(signupAuthSignupPostBodyUsernameMin).max(signupAuthSignupPostBodyUsernameMax),
  "email": zod.email(),
  "password": zod.string().min(signupAuthSignupPostBodyPasswordMin)
})


/**
 * @summary Login
 */
export const loginAuthLoginPostResponseTokenTypeDefault = `bearer`;

export const LoginAuthLoginPostResponse = zod.object({
  "access_token": zod.string(),
  "token_type": zod.string().default(loginAuthLoginPostResponseTokenTypeDefault)
})


/**
 * @summary Refresh
 */
export const refreshAuthRefreshPostResponseTokenTypeDefault = `bearer`;

export const RefreshAuthRefreshPostResponse = zod.object({
  "access_token": zod.string(),
  "token_type": zod.string().default(refreshAuthRefreshPostResponseTokenTypeDefault)
})


/**
 * @summary Get Me
 */
export const GetMeAuthMeGetResponse = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string()
})


/**
 * @summary Update Me
 */
export const updateMeAuthMePutBodyUsernameMin = 3;
export const updateMeAuthMePutBodyUsernameMax = 150;



export const UpdateMeAuthMePutBody = zod.object({
  "username": zod.string().min(updateMeAuthMePutBodyUsernameMin).max(updateMeAuthMePutBodyUsernameMax)
})

export const UpdateMeAuthMePutResponse = zod.object({
  "id": zod.number(),
  "username": zod.string(),
  "email": zod.string()
})


/**
 * @summary Request Password Reset
 */
export const RequestPasswordResetAuthPasswordResetRequestPostBody = zod.object({
  "email": zod.email()
})


/**
 * @summary Confirm Password Reset
 */
export const confirmPasswordResetAuthPasswordResetConfirmPostBodyNewPasswordMin = 8;



export const ConfirmPasswordResetAuthPasswordResetConfirmPostBody = zod.object({
  "token": zod.string(),
  "new_password": zod.string().min(confirmPasswordResetAuthPasswordResetConfirmPostBodyNewPasswordMin)
})

export const ConfirmPasswordResetAuthPasswordResetConfirmPostResponse = zod.unknown()


/**
 * @summary List Statuses
 */
export const listStatusesStatusesGetResponseStatusesItemNameMax = 50;

export const listStatusesStatusesGetResponseStatusesItemColorMax = 7;



export const ListStatusesStatusesGetResponse = zod.object({
  "statuses": zod.array(zod.object({
  "name": zod.string().min(1).max(listStatusesStatusesGetResponseStatusesItemNameMax),
  "color": zod.string().max(listStatusesStatusesGetResponseStatusesItemColorMax),
  "id": zod.number(),
  "order": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('ステータスレスポンス用スキーマ'))
}).describe('ステータス一覧レスポンス用スキーマ')


/**
 * @summary Create Status
 */
export const createStatusStatusesPostBodyNameMax = 50;

export const createStatusStatusesPostBodyColorMax = 7;



export const CreateStatusStatusesPostBody = zod.object({
  "name": zod.string().min(1).max(createStatusStatusesPostBodyNameMax),
  "color": zod.string().max(createStatusStatusesPostBodyColorMax)
}).describe('ステータス作成用スキーマ')


/**
 * @summary Get Status
 */
export const GetStatusStatusesStatusIdGetParams = zod.object({
  "status_id": zod.number()
})

export const getStatusStatusesStatusIdGetResponseNameMax = 50;

export const getStatusStatusesStatusIdGetResponseColorMax = 7;



export const GetStatusStatusesStatusIdGetResponse = zod.object({
  "name": zod.string().min(1).max(getStatusStatusesStatusIdGetResponseNameMax),
  "color": zod.string().max(getStatusStatusesStatusIdGetResponseColorMax),
  "id": zod.number(),
  "order": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('ステータスレスポンス用スキーマ')


/**
 * @summary Update Status
 */
export const UpdateStatusStatusesStatusIdPutParams = zod.object({
  "status_id": zod.number()
})

export const updateStatusStatusesStatusIdPutBodyNameMax = 50;

export const updateStatusStatusesStatusIdPutBodyColorMax = 7;



export const UpdateStatusStatusesStatusIdPutBody = zod.object({
  "name": zod.string().min(1).max(updateStatusStatusesStatusIdPutBodyNameMax),
  "color": zod.string().max(updateStatusStatusesStatusIdPutBodyColorMax)
}).describe('ステータス更新用スキーマ')

export const updateStatusStatusesStatusIdPutResponseNameMax = 50;

export const updateStatusStatusesStatusIdPutResponseColorMax = 7;



export const UpdateStatusStatusesStatusIdPutResponse = zod.object({
  "name": zod.string().min(1).max(updateStatusStatusesStatusIdPutResponseNameMax),
  "color": zod.string().max(updateStatusStatusesStatusIdPutResponseColorMax),
  "id": zod.number(),
  "order": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('ステータスレスポンス用スキーマ')


/**
 * @summary Delete Status
 */
export const DeleteStatusStatusesStatusIdDeleteParams = zod.object({
  "status_id": zod.number()
})


/**
 * @summary Reorder Statuses
 */



export const ReorderStatusesStatusesReorderPutBody = zod.object({
  "order": zod.array(zod.number()).min(1).describe('並び順のステータスIDリスト')
}).describe('ステータス並び替え用スキーマ')

export const reorderStatusesStatusesReorderPutResponseStatusesItemNameMax = 50;

export const reorderStatusesStatusesReorderPutResponseStatusesItemColorMax = 7;



export const ReorderStatusesStatusesReorderPutResponse = zod.object({
  "statuses": zod.array(zod.object({
  "name": zod.string().min(1).max(reorderStatusesStatusesReorderPutResponseStatusesItemNameMax),
  "color": zod.string().max(reorderStatusesStatusesReorderPutResponseStatusesItemColorMax),
  "id": zod.number(),
  "order": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('ステータスレスポンス用スキーマ'))
}).describe('ステータス一覧レスポンス用スキーマ')


/**
 * タスク一覧取得（締切日でソート）
 * @summary List Tasks
 */
export const ListTasksTasksGetQueryParams = zod.object({
  "order": zod.enum(['asc', 'desc']).optional(),
  "q": zod.union([zod.string(),zod.null()]).optional()
})

export const listTasksTasksGetResponseTasksItemTitleMax = 255;



export const ListTasksTasksGetResponse = zod.object({
  "tasks": zod.array(zod.object({
  "title": zod.string().min(1).max(listTasksTasksGetResponseTasksItemTitleMax),
  "content": zod.string(),
  "due_date": zod.iso.date(),
  "status_id": zod.number(),
  "id": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('タスクレスポンス用スキーマ'))
}).describe('タスク一覧レスポンス用スキーマ')


/**
 * タスク作成
 * @summary Create Task
 */
export const createTaskTasksPostBodyTitleMax = 255;



export const CreateTaskTasksPostBody = zod.object({
  "title": zod.string().min(1).max(createTaskTasksPostBodyTitleMax),
  "content": zod.string(),
  "due_date": zod.iso.date(),
  "status_id": zod.number()
}).describe('タスク作成用スキーマ')


/**
 * タスク詳細取得
 * @summary Get Task
 */
export const GetTaskTasksTaskIdGetParams = zod.object({
  "task_id": zod.number()
})

export const getTaskTasksTaskIdGetResponseTitleMax = 255;



export const GetTaskTasksTaskIdGetResponse = zod.object({
  "title": zod.string().min(1).max(getTaskTasksTaskIdGetResponseTitleMax),
  "content": zod.string(),
  "due_date": zod.iso.date(),
  "status_id": zod.number(),
  "id": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('タスクレスポンス用スキーマ')


/**
 * タスク更新
 * @summary Update Task
 */
export const UpdateTaskTasksTaskIdPutParams = zod.object({
  "task_id": zod.number()
})

export const updateTaskTasksTaskIdPutBodyTitleMax = 255;



export const UpdateTaskTasksTaskIdPutBody = zod.object({
  "title": zod.string().min(1).max(updateTaskTasksTaskIdPutBodyTitleMax),
  "content": zod.string(),
  "due_date": zod.iso.date(),
  "status_id": zod.number()
}).describe('タスク更新用スキーマ')

export const updateTaskTasksTaskIdPutResponseTitleMax = 255;



export const UpdateTaskTasksTaskIdPutResponse = zod.object({
  "title": zod.string().min(1).max(updateTaskTasksTaskIdPutResponseTitleMax),
  "content": zod.string(),
  "due_date": zod.iso.date(),
  "status_id": zod.number(),
  "id": zod.number(),
  "created_at": zod.iso.datetime({}),
  "updated_at": zod.iso.datetime({})
}).describe('タスクレスポンス用スキーマ')


/**
 * タスク削除
 * @summary Delete Task
 */
export const DeleteTaskTasksTaskIdDeleteParams = zod.object({
  "task_id": zod.number()
})
